#ifndef PLAYERCONFIG_H
#define PLAYERCONFIG_H

#define PLAYER_MOVEMENT_SPEED (1.0f / 20.0f)
#define PLAYER_ROTATION_SPEED (3 * DEG2RAD)
#define PLAYER_FOV 60 * DEG2RAD
#define PLAYER_MOVEMENT_SPEED_SPRINT_LIMIT (1.8f / 20.0f)

#endif